export const formulaEvidenceCatalog = [
  entry('path', 'implementation', 'implemented', true, ['OHLCV'], ['returns', 'vwap'], []),
  entry('cost', 'blog-source', 'implemented', true, ['OHLCV'], ['costAnchor', 'costBand'], []),
  entry(
    'volatility',
    'blog-source',
    'implemented',
    true,
    ['returns', 'trueRange'],
    ['annualVol', 'atrPercent'],
    ['hgjrvacjbe'],
  ),
  entry(
    'delta-band',
    'desmos-source',
    'implemented',
    true,
    ['entryPrice', 'formulaHorizonSessions', 'iv', 'deltaSlope'],
    ['longBand', 'shortBand'],
    ['943334771f', '5baa5607d0', '83418c6ca1'],
  ),
  entry(
    'option-greeks',
    'paper',
    'research-only',
    false,
    ['entryPrice', 'strikePrice', 'timeToExpirySessions', 'iv'],
    ['price', 'greeks'],
    ['black-scholes-1973', '97fa8c814b'],
    ['real-option-leg'],
    {
      assumptions: ['volatility input is scenario sigma unless a market quote source is attached'],
      invalidWhen: ['missing contract multiplier or settlement rules', 'model premium presented as executed premium'],
    },
  ),
  entry(
    'asian-option',
    'paper',
    'research-only',
    false,
    ['entryPrice', 'strikePrice', 'timeToExpirySessions', 'iv'],
    ['asianPrice', 'bachelierPrice'],
    ['bachelier-1900', '0711.1272'],
    ['listed-contract-rules'],
  ),
  entry(
    'lp-inventory',
    'protocol-whitepaper',
    'research-only',
    false,
    ['markPrice', 'lowerPrice', 'upperPrice', 'liquidity'],
    ['token0', 'token1', 'value', 'inventoryDeltaToken0'],
    ['uniswap-v3-whitepaper', 'atis-elsts-v3-liquidity-math'],
    ['real-lp-position'],
  ),
  entry(
    'lp-research-range',
    'heuristic',
    'research-only',
    false,
    ['adaptiveCostAnchor', 'GetDelta.rT', 'formulaHorizonSessions', 'realizedVolatility'],
    ['lpResearchLowerPrice', 'lpResearchUpperPrice'],
    ['943334771f', 'uniswap-v3-whitepaper'],
    [],
    {
      assumptions: ['range geometry only; no liquidity or position is implied'],
      invalidWhen: ['display range is presented as real LP inventory, fees, IL or PnL'],
    },
  ),
  entry(
    'lp-pool-coverage',
    'real-data-snapshot',
    'research-only',
    false,
    ['poolCoverage.reserveUsd', 'poolCoverage.volumeUsd24h', 'poolCoverage.topPoolReserveShare'],
    ['turnover24h', 'topReserveShare'],
    ['geckoterminal-pool-aggregate'],
    ['tick-liquidity-history', 'lp-add-remove-events'],
  ),
  entry(
    'liquidity-fingerprint',
    'desmos-source',
    'research-only',
    false,
    [
      'distribution',
      'range',
      'segmentCount',
      'activePrice',
      'costAnchor',
      'orderLevels',
      'volatility',
      'tradingDaysPerYear',
    ],
    ['componentDensity', 'targetAllocationWeights', 'fingerprintStats'],
    ['0a40cbb0ee', '06b68e5e0e'],
    ['real-ticks', 'lp-nft-weights', 'order-book-depth'],
    {
      assumptions: [
        'normalized over the displayed range',
        'weights express target allocation rather than a price forecast',
      ],
      invalidWhen: [
        'interpreted as probability of future price',
        'aggregate pool quotes interpreted as tick liquidity',
      ],
    },
  ),
  entry(
    'amm-geometry',
    'desmos-source',
    'protocol-unverified',
    false,
    ['reserveSnapshot', 'invariantParameters'],
    ['ammCurve', 'numoenSnapshot'],
    ['50693ae997', '8a2d4257ef'],
    ['verified-protocol-mechanics'],
  ),
  entry(
    'capital-efficiency',
    'desmos-source',
    'research-only',
    false,
    ['rangeWidth', 'skew', 'valuationPriceBasis'],
    ['efficiencyAtGeometricMidpoint', 'efficiencyAtArithmeticCenter', 'frontierSlope', 'ckSymmetricInflection'],
    ['ysv2j74j6k', '5ab9c1e3a1'],
    [],
    {
      assumptions: [
        'CK theorem uses arithmetic bounds Pa=P0(1-x), Pb=P0(1+x) and skew=1',
        'the endpoint-ratio CE curve is valued at the range geometric midpoint sqrt(PaPb), while P0 is only the arithmetic width coordinate',
        'capital efficiency is a geometric multiplier',
      ],
      invalidWhen: [
        '84.13 percent is labelled as probability coverage',
        '84.13 percent is presented as fee or PnL optimum',
        'geometric-midpoint CE is presented as CE at arithmetic-center current price',
        'skew is not 1 but the symmetric CK point is presented as the current frontier',
      ],
    },
  ),
  entry(
    'funding',
    'paper',
    'proxy-only',
    false,
    ['perpTwap', 'spotTwap', 'hours'],
    ['basisFraction', 'cumulativeFundingProxy'],
    ['fundamentals-perpetual-futures'],
    ['exchange-schedule', 'settlement-history'],
  ),
  entry(
    'portfolio',
    'paper',
    'research-only',
    false,
    ['lpLeg', 'optionLeg', 'hedgeLeg', 'fees', 'funding'],
    ['markLedger', 'entryCashflowLedger', 'pnlLedger'],
    ['constant-product-amm-math'],
    ['leg-lifecycle', 'fee-model'],
    {
      assumptions: ['all PnL legs share one currency, horizon and capital basis'],
      invalidWhen: ['gross option mark is added to LP PnL', 'missing premium is treated as zero'],
    },
  ),
  entry(
    'order-plan',
    'implementation',
    'implemented',
    true,
    ['costBand', 'deltaBand', 'account'],
    ['orders', 'invalidation'],
    [],
  ),
  entry(
    'deviation-score',
    'statistical-reference',
    'implemented',
    true,
    ['costDistance', 'annualVol', 'formulaHorizonSessions'],
    ['zScore', 'deviationPercentile', 'twoSidedTailProbability', 'strength'],
    [],
    [],
    {
      assumptions: ['normal distribution is only a reference scale for extremeness'],
      invalidWhen: ['normal tail mass is labelled as probability of future mean reversion'],
    },
  ),
  entry(
    'risk-surface',
    'paper',
    'implemented',
    false,
    ['bandLow', 'bandHigh', 'iv'],
    ['greekCurves'],
    ['black-scholes-1973'],
  ),
  entry(
    'net-lp-efficiency',
    'accounting-decomposition',
    'research-only',
    false,
    ['capitalEfficiency', 'lpIlFraction', 'ilModel', 'capitalBasis', 'pathFeeReturn', 'horizonSessions'],
    ['geometry', 'returnAttribution', 'missingInputs'],
    ['uniswap-v3-whitepaper'],
    ['fee-growth', 'volume-path', 'lp-share', 'gas', 'rebalance-rules'],
    {
      assumptions: [
        'fee and IL returns must use the same horizon and initial-capital basis',
        'fee versus theta is an analogy only after currency, horizon and notional normalization',
      ],
      invalidWhen: ['capital efficiency multiplier is added to a return', 'fee tier is treated as realized fee income'],
    },
  ),
  entry(
    'net-carry',
    'heuristic',
    'proxy-only',
    false,
    ['costDistance', 'cumulativeFundingProxy'],
    ['netReturn'],
    [],
    ['exchange-schedule'],
  ),
  entry('mean-reversion', 'heuristic', 'implemented', false, ['costDistanceSeries'], ['halfLife'], []),
  entry(
    'dynamic-holding-state',
    'heuristic',
    'implemented',
    false,
    [
      'drawdownDepth',
      'drawdownSpeedFast',
      'drawdownSpeedSlow',
      'drawdownRepair',
      'zScore',
      'halfLifeSessions',
      'costLower',
      'costAnchor',
    ],
    ['phase', 'milestones', 'expectation', 'holdingPlan', 'blockedReasons'],
    [],
  ),
  entry('gamma-pnl', 'paper', 'implemented', false, ['gamma', 'priceChange'], ['gammaPnl'], ['black-scholes-1973']),
  entry('vol-confidence', 'heuristic', 'implemented', false, ['annualVol', 'sampleSize'], ['confidenceRange'], []),
]

export function getFormulaEvidence(id) {
  return formulaEvidenceCatalog.find((item) => item.id === id) ?? null
}

function entry(id, sourceTier, status, executable, inputs, outputs, sources, missingInputs = [], details = {}) {
  const executionDecision = id === 'order-plan'
  const executionInput = executable && !executionDecision
  return {
    id,
    sourceTier,
    status,
    executable,
    executionInput,
    executionDecision,
    queryOnly: !executable,
    inputs,
    outputs,
    sources,
    missingInputs,
    assumptions: details.assumptions ?? [],
    invalidWhen: details.invalidWhen ?? [],
  }
}
