export const formulaStages = [
  {
    id: 'path',
    layer: '数据',
    label: '价格路径',
    role: '所有公式的共同输入口径',
    inputs: ['OHLCV', '成交量', '时间粒度'],
    outputs: ['对数收益', 'VWAP', '路径窗口'],
    formulas: ['r_t = ln(P_t / P_{t-1})', 'VWAP = sum(PV) / sum(V)', '时间基: 质数 179 / e / π 分解周期'],
    sources: [],
    status: 'implemented',
    feeds: ['cost', 'volatility'],
  },
  {
    id: 'cost',
    layer: '数据',
    label: '市场成本',
    role: '把路径翻译成可交易的成本锚和动态成本带',
    inputs: ['OHLCV', '窗口长度'],
    outputs: ['成本锚', '近端成本', '成本上沿', '成本下沿'],
    formulas: ['Cost_vwap = sum(close * volume) / sum(volume)', 'd_cost = close / Cost_vwap - 1'],
    sources: [],
    status: 'implemented',
    feeds: ['delta-band', 'order-plan', 'portfolio'],
  },
  {
    id: 'volatility',
    layer: '波动',
    label: '波动口径',
    role: '决定挂单间距、期权口径和失效阈值',
    inputs: ['对数收益', 'high/low/close'],
    outputs: ['年化波动', 'ATR', 'VixFix'],
    formulas: ['sigma_ann = std(r_t) * sqrt(365)', 'ATR% = avg(TR / close)', 'VixFix = (highest(close,N)-low)/highest(close,N)'],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['delta-band', 'option-greeks', 'order-plan'],
  },
  {
    id: 'delta-band',
    layer: '波动',
    label: 'GetDelta 成本带',
    role: '用任意入场价、持仓/到期时间、IV 和目标增量 d 生成多空价格带',
    inputs: ['入场价 P', '持仓 T', 'IV/s', '目标增量 deltaSlope'],
    outputs: ['多头高/成本/低', '空头高/成本/低'],
    formulas: ['e_T = sqrt(T / (365 * 2pi))', 'r_T = ((1 + sigma e_T) / (1 - sigma e_T))^2 * z', 'K = P(d r_T - d + 1)^2 / r_T'],
    sources: ['943334771f', '5baa5607d0', '83418c6ca1'],
    status: 'implemented',
    feeds: ['order-plan', 'portfolio'],
  },
  {
    id: 'option-greeks',
    layer: '期权',
    label: '期权 Greeks',
    role: '把单腿和多腿期权组合拆成可检查的局部敏感度和 payoff 曲线',
    inputs: ['标的价', '多 leg 行权价/方向/数量', '持仓 T', 'IV', '利率', '分红/资金口径 q'],
    outputs: ['组合价格', '组合 Delta', '组合 Gamma', 'Theta/日', 'Theta/年', 'Vega', 'Rho', '场景 payoff'],
    formulas: ['leg_i = side_i · qty_i · Option_i(S,K_i,T,σ)', 'Portfolio = Σ leg_i', 'Greeks = Σ side_i · qty_i · Greeks_i'],
    sources: ['black-scholes-1973', '97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'research-only',
    feeds: ['portfolio'],
  },
  {
    id: 'asian-option',
    layer: '期权',
    label: '亚式近似',
    role: '处理均价结算、Bachelier normal-vol 和 LP payoff 的平滑比较',
    inputs: ['价格路径', '均价窗口', 'IV', 'normal vol', '行权价'],
    outputs: ['Asian price/Delta/Gamma', 'Bachelier price/Delta/Gamma', 'payoff fit 边界'],
    formulas: ['sigma_geo ≈ sigma / sqrt(3)', 'Bachelier: C=e^{-rT}((S-K)N(d)+sigma_N sqrt(T)n(d))', 'd=(S-K)/(sigma_N sqrt(T))'],
    sources: ['97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'lp-inventory',
    layer: 'LP',
    label: 'LP 库存曲线',
    role: '直接计算 LP 持有什么库存，而不是只看无常损失标签',
    inputs: ['价格', '区间下沿', '区间上沿', '流动性 L'],
    outputs: ['x_real', 'y_real', 'LP 价值', '库存 Delta'],
    formulas: ['x = L/sqrt(p) - L/sqrt(p_u)', 'y = L sqrt(p) - L sqrt(p_l)', 'V_lp = xp + y', 'V(p) piecewise: p | (2√(pKr)-p-K)/(r-1) | K', 'v(x)=E(V(x)-V(S₀))-H(x-S₀)+F·S₀', 'IL=(V_lp-V_hold)/V_hold', 'V_blp=-2L√x'],
    sources: ['936edf03fb', '3f634650d0', '0159507098', '825122fb8a'],
    status: 'research-only',
    feeds: ['liquidity-fingerprint', 'portfolio', 'capital-efficiency'],
  },
  {
    id: 'liquidity-fingerprint',
    layer: 'LP',
    label: '流动性指纹',
    role: '模型目标仓：展示目标 LP 密度和本策略挂单刻度；不是市场盘口或链上真实 LP 构成',
    inputs: ['OHLCV 成本锚', '目标分布', '现价', '成本锚', 'Delta/LP 区间', '模拟挂单'],
    outputs: ['混合成分密度', '价格层级', '成分质量占比', '指纹统计', '缺失数据提示'],
    formulas: ['f(p)=Σ w_c f_c(p)/∫f_c', 'L_i = ∫_{range_i} f(p) dp / ∫_{lower}^{upper} f(p) dp', 'f_logLaplace(p)=Laplace(log(p); mu, lambda, kappa)', 'f_anchor(p)=Normal(log(p); log(anchor), sigma)', '待补: 真实 tick 边界、手续费层级、链上 LP 权重'],
    sources: ['0a40cbb0ee', '06b68e5e0e', 'hgjrvacjbe', 'bb63abc148'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'amm-geometry',
    layer: 'AMM',
    label: 'AMM 几何',
    role: '研究不变量、储备曲线、Lambert W 与 Numoen AMM 几何；Numoen 协议机制未验证',
    inputs: ['储备', '不变量', '边界条件'],
    outputs: ['xy=k', 'Lambert W 分支', 'Numoen quoter', 'slippage snapshot'],
    formulas: ['x y = k', 'W(z) e^{W(z)} = z', 'Lambert curve: y = W(c e^{c(2-x)} / x) / c', 'Numoen: x/(s·10^3) - (y/s)^2/4 + u·y/s = L'],
    sources: ['50693ae997', '8a2d4257ef', 'c1a8cc5a49', 'cb14bde283'],
    status: 'protocol-unverified',
    feeds: [],
  },
  {
    id: 'capital-efficiency',
    layer: 'LP',
    label: '资本效率',
    role: '比较区间收窄带来的资金效率和维护压力',
    inputs: ['区间宽度', '偏斜'],
    outputs: ['效率倍数', '上下界'],
    formulas: ['CE(x, alpha) = 1 / (1 - ((1-x)/(1+alpha x))^(1/4))'],
    sources: ['696b78e1fd', '5ab9c1e3a1'],
    status: 'research-only',
    feeds: ['portfolio'],
  },
  {
    id: 'funding',
    layer: '组合',
    label: '资金费率',
    role: '仅展示 TWAP 估计；未接真实永续资金费率、结算周期和交易所制度',
    inputs: ['perp TWAP', 'spot TWAP', '估计小时'],
    outputs: ['basisEstimate', 'fundingProxy', 'cumulativeFundingEstimate'],
    formulas: ['basisEstimate = perp_twap / spot_twap - 1', 'fundingProxy = basisEstimate', 'cumulativeFundingEstimate = fundingProxy × h / 24'],
    sources: ['fundamentals-perpetual-futures'],
    status: 'proxy-only',
    feeds: [],
  },
  {
    id: 'portfolio',
    layer: '组合',
    label: '组合研究',
    role: '组合研究视图；不作为模拟挂单的输入',
    inputs: ['LP 价值', '期权价值', '对冲规模', '手续费', '资金费率'],
    outputs: ['组合曲线', '局部 Delta', '盈亏路径'],
    formulas: ['Portfolio(p)=LP(p)+Option(p)-H(p-p0)+Fees-Funding', 'curve(p)=lpPnl(p)+optionLeg(p)+hedgePnl(p)+fees-funding'],
    sources: ['99af67bf76', '0e2beceb89', '722e20ccc4', '825122fb8a', '0159507098', '3f634650d0'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'order-plan',
    layer: '执行',
    label: '模拟挂单',
    role: '只在成本带、GetDelta 带和账户输入同时满足时生成模拟挂单',
    inputs: ['成本带', 'GetDelta 带', '本金', '失效条件'],
    outputs: ['挂买', '挂卖', '观察窗口', '失效线'],
    formulas: ['orders = f(cost_path, delta_band, capital, risk_state)'],
    sources: [],
    status: 'implemented',
    feeds: [],
  },
  {
    id: 'deviation-score',
    layer: '融合',
    label: '偏离强度',
    role: 'Cost × Volatility：价格偏离成本锚的标准差倍数，回归概率估计',
    inputs: ['成本偏离', '年化波动', '持仓天数'],
    outputs: ['z-score', '回归概率', '偏离强度等级'],
    formulas: ['z = costDistance / (σ·√(T/365))', 'P(回归) = Φ(|z|)'],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'risk-surface',
    layer: '融合',
    label: '风险曲面',
    role: 'Delta Band × Option Greeks：在价格带上展开 Greeks 曲线',
    inputs: ['入场价', '行权价', 'IV', '价格带下沿', '价格带上沿'],
    outputs: ['Delta 曲线', 'Gamma 曲线', 'Theta 曲线'],
    formulas: ['Greeks(price) for price ∈ [bandLow, bandHigh]'],
    sources: ['943334771f', '97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'net-lp-efficiency',
    layer: '融合',
    label: 'LP 净效率',
    role: 'IL × CE 的研究视图；未完成真实 LP 区间权重、手续费和再平衡规则',
    inputs: ['资本效率', '无常损失', '预期手续费'],
    outputs: ['毛效率估计', '净效率估计', '研究提示'],
    formulas: ['research net = (CE-1) + IL + CE·fee', '待补: 区间权重、手续费制度、离散 LP 规则'],
    sources: ['696b78e1fd', '825122fb8a'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'net-carry',
    layer: '融合',
    label: '持仓净收益',
    role: 'Funding × Cost 的研究视图；资金费率未接真实结算制度',
    inputs: ['成本偏离', '资金费率', '持仓天数'],
    outputs: ['净收益估计', '资金成本估计', '研究提示'],
    formulas: ['research net = |costDistance| - |cumulativeFundingEstimate|', 'breakEvenFunding = |fundingCost|', '待补: 真实资金费率、结算时间、交易所制度'],
    sources: [],
    status: 'proxy-only',
    feeds: [],
  },
  {
    id: 'mean-reversion',
    layer: '二阶',
    label: '均值回归半衰期',
    role: 'e/π/质数结构：AR(1) 估计回归速度，半衰期 = ln(2)/θ，以质数天衡量',
    inputs: ['成本偏离序列', '年时间基'],
    outputs: ['ρ 自回归系数', 'θ 回归速度', '半衰期天数', '速度评级', '短线回补窗口', '结构目标持仓时间'],
    formulas: ['x_t = ρ·x_{t-1} + ε', 'θ = -ln(|ρ|)', 't½ = ln(2)/θ', 'q = (targetPrice-entryPrice)/(anchorPrice-entryPrice)', 'holdDays(q) = t½·log2(1/(1-q))'],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'dynamic-holding-state',
    layer: '二阶',
    label: '动态持仓状态',
    role: '用回撤表征、z、HL、成本锚和 LP 上沿推导观察/等待/剔除及短线/基金周期',
    inputs: ['drawdownDepth/speed/repair/age', 'z-score', '半衰期 HL', '成本下沿/成本锚', 'LP 上沿'],
    outputs: ['phase', 'milestones', 'expectation', 'holdingPlan', 'blockedReasons'],
    formulas: ['drawdownDepth = close / high120 - 1', 'q(T)=1-2^(-T/HL)', 'q = (targetPrice-entryPrice)/(anchorPrice-entryPrice)', 'holdDays(q) = HL·log2(1/(1-q))'],
    sources: [],
    status: 'implemented',
    feeds: ['order-plan'],
  },
  {
    id: 'gamma-pnl',
    layer: '二阶',
    label: 'Gamma PnL / 凸性收益',
    role: '½·Γ·(ΔP)² ：凸性头寸的实际波动收益，连接方差结构与 π',
    inputs: ['Gamma', '价格变动', '仓位规模'],
    outputs: ['Dollar Gamma', 'Gamma PnL', '凸性方向'],
    formulas: ['GammaPnL = ½ · Γ · (ΔP)² · positionSize'],
    sources: ['97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'vol-confidence',
    layer: '二阶',
    label: '波动率区间',
    role: 'σ 的估计误差 ≈ σ/√(2n)：展示样本波动率的区间误差',
    inputs: ['年化波动', '样本量', '区间水平'],
    outputs: ['标准误', '估计区间', '精度评级'],
    formulas: ['SE(σ) = σ / √(2n)', 'CI = σ ± z·SE'],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['volatility'],
  },
]

export const formulaEdges = formulaStages.flatMap((stage) =>
  stage.feeds.map((target) => ({ source: stage.id, target })),
)

export const formulaCapabilities = [
  {
    id: 'market-path',
    label: '市场路径引擎',
    role: '把 K 线统一成成本、波动和公式路径',
    stages: ['path', 'cost', 'volatility'],
    action: '回答现在离市场成本有多远，波动是否允许挂单。',
  },
  {
    id: 'move-derivative',
    label: '波动定价引擎',
    role: '把任意入场价和持仓时间翻成价格带、期权敏感度和均价结构',
    stages: ['delta-band', 'option-greeks', 'asian-option'],
    action: '回答应该给价格留多宽、风险曲率来自哪里。',
  },
  {
    id: 'liquidity-amm',
    label: '流动性库存引擎',
    role: '把 LP、AMM 不变量和流动性分布放到同一套库存语言里',
    stages: ['lp-inventory', 'liquidity-fingerprint', 'amm-geometry', 'capital-efficiency'],
    action: '回答 LP 实际持仓、区间效率和再平衡压力。',
  },
  {
    id: 'portfolio-execution',
    label: '组合执行引擎',
    role: '模拟挂单只接成本带、GetDelta 和账户输入；LP/期权/永续仍是研究视图',
    stages: ['funding', 'portfolio', 'order-plan'],
    action: '回答模拟挂单刻度、持仓窗口和失效线；组合研究不参与模拟挂单。',
  },
  {
    id: 'formula-fusion',
    label: '公式融合',
    role: '将两个以上基础公式融合成研究视图，未进入模拟挂单',
    stages: ['deviation-score', 'risk-surface', 'net-lp-efficiency', 'net-carry'],
    action: '回答偏离和风险曲面的观察，不输出默认策略结论。',
  },
  {
    id: 'second-order',
    label: '二阶分析',
    role: '速度 · 凸性 · 不确定性：均值回归、凸性项和波动率区间',
    stages: ['mean-reversion', 'dynamic-holding-state', 'gamma-pnl', 'vol-confidence'],
    action: '回答回归速度、动态持仓状态、Gamma 收益和波动率区间——e/π/质数结构在此体现。',
  },
]

export function getFormulaCapability(id) {
  return formulaCapabilities.find((item) => item.id === id) ?? formulaCapabilities[0]
}

export function getCapabilityStages(capabilityId) {
  const capability = getFormulaCapability(capabilityId)
  return capability.stages.map(getFormulaStage)
}

export function getFormulaStage(id) {
  return formulaStages.find((stage) => stage.id === id) ?? formulaStages[0]
}
