export const formulaStages = [
  {
    id: 'path',
    layer: '数据',
    label: '价格路径',
    role: '把截至当前会话已观察到的 OHLCV 组织为因果前缀，作为所有下游公式的共同输入口径',
    inputs: ['截至会话 t 的 OHLCV', '成交量', '市场时间粒度'],
    outputs: ['对数收益 r_t', '因果前缀 VWAP_t', '可见前缀窗口状态'],
    formulas: [
      'r_t = ln(P_t / P_{t-1})',
      'VWAP_t = Σ_{i≤t}(P_i·V_i) / Σ_{i≤t}V_i',
      'pathState_t = f(OHLCV_{0:t}); 禁止读取 t 之后的样本',
    ],
    sources: [],
    status: 'implemented',
    feeds: ['cost', 'volatility'],
  },
  {
    id: 'cost',
    layer: '数据',
    label: '市场成本',
    role: '把路径翻译成可交易的成本锚和动态成本带',
    inputs: ['OHLCV', '窗口长度'],
    outputs: ['成本锚', '近端成本', '成本上沿', '成本下沿'],
    formulas: [
      'typical_i = (high_i + low_i + close_i) / 3',
      'Cost_vwap = sum(typical_i * volume_i) / sum(volume_i); 全零成交量时退化为 equal-weight typical mean',
      'd_cost = close / Cost_vwap - 1',
    ],
    sources: [],
    status: 'implemented',
    feeds: ['delta-band', 'order-plan', 'portfolio'],
  },
  {
    id: 'volatility',
    layer: '波动',
    label: '波动口径',
    role: '决定挂单间距、期权口径和失效阈值',
    inputs: ['对数收益', 'high/low/close', '市场年交易会话数 tradingDaysPerYear'],
    outputs: ['年化波动', 'ATR', 'VixFix'],
    formulas: [
      'sigma_ann = std(r_t) * sqrt(tradingDaysPerYear)',
      'ATR% = avg(TR / close)',
      'VixFix = (highest(close,N)-low)/highest(close,N)',
    ],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['delta-band', 'option-greeks', 'order-plan'],
  },
  {
    id: 'delta-band',
    layer: '波动',
    label: 'GetDelta 成本带',
    role: '用任意入场价、方向/结构目标绑定的公式周期、IV 和局部斜率 d 生成多空价格带',
    inputs: [
      '入场价 P',
      '公式周期 formulaHorizonSessions（交易会话）',
      '市场年交易会话数 tradingDaysPerYear',
      'IV/s（年化）',
      '局部斜率 deltaSlope',
    ],
    outputs: ['多头高/成本/低', '空头高/成本/低'],
    formulas: [
      'e_H = sqrt(formulaHorizonSessions / (tradingDaysPerYear · 2π))',
      'r_H = ((1 + σ·e_H) / (1 - σ·e_H))² · z',
      'K = P(d·r_H - d + 1)² / r_H',
    ],
    sources: ['943334771f', '5baa5607d0', '83418c6ca1'],
    status: 'implemented',
    feeds: ['order-plan', 'portfolio'],
  },
  {
    id: 'option-greeks',
    layer: '期权',
    label: '期权 Greeks',
    role: '把单腿和多腿期权组合拆成可检查的局部敏感度和 payoff 曲线',
    inputs: [
      '标的价（报价币/标的单位）',
      '多 leg 行权价/方向/期权单位数量',
      'contractMultiplier（标的单位/期权合约）',
      '独立期权距到期会话 timeToExpirySessions',
      '市场年交易会话数 tradingDaysPerYear',
      'IV（年化小数）',
      '无风险利率/分红率（年化小数）',
    ],
    outputs: [
      'portfolio.value（报价币；含数量与 contractMultiplier）',
      'portfolio.optionDelta（标的单位；含数量与 contractMultiplier）',
      'portfolio.optionGamma（标的单位/标的价格单位；含数量与 contractMultiplier）',
      'portfolio.optionThetaPerSession（报价币/交易会话；含数量与 contractMultiplier）',
      'portfolio.optionThetaAnnual（报价币/年；含数量与 contractMultiplier）',
      'portfolio.optionVegaPerPct（报价币/IV 上升 1 个百分点）',
      'portfolio.optionRhoPerPct（报价币/年化利率上升 1 个百分点）',
      'points[].modelPnl / expiryPnl（报价币；含数量与 contractMultiplier）',
    ],
    formulas: [
      'leg_i = side_i · qty_i · Option_i(S,K_i,T,σ)',
      'Portfolio = Σ leg_i',
      'Greeks = Σ side_i · qty_i · Greeks_i',
    ],
    sources: ['black-scholes-1973', '97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'research-only',
    feeds: ['portfolio'],
  },
  {
    id: 'asian-option',
    layer: '期权',
    label: '亚式近似',
    role: '处理均价结算、Bachelier normal-vol 和 LP payoff 的平滑比较',
    inputs: ['价格路径', '均价窗口', 'IV（年化小数）', 'normal vol（报价币/√年）', '行权价'],
    outputs: [
      'Asian price（报价币/期权单位）',
      'Asian optionDelta（标的单位/期权单位）',
      'Asian optionGamma（optionDelta/标的价格单位）',
      'Bachelier price/optionDelta/optionGamma（同上单位）',
      'Bachelier optionNormalVegaPerUnit（normal-vol 单位；不可与 BSM optionVegaPerPct 直接相加）',
      'payoff fit 边界',
    ],
    formulas: [
      'sigma_geo ≈ sigma / sqrt(3)',
      'Bachelier: C=e^{-rT}((S-K)N(d)+sigma_N sqrt(T)n(d))',
      'd=(S-K)/(sigma_N sqrt(T))',
    ],
    sources: ['97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'lp-inventory',
    layer: 'LP',
    label: 'LP 库存曲线',
    role: '在已声明研究情景或完整带时间定位的真实仓位下，计算 LP 库存；不把池聚合报价当作用户头寸',
    inputs: ['价格', '区间下沿', '区间上沿', '流动性 L', '已声明 LP 研究情景或完整真实仓位'],
    outputs: ['x_real', 'y_real', 'LP 价值', '库存 Delta'],
    formulas: [
      'x = L/sqrt(p) - L/sqrt(p_u)',
      'y = L sqrt(p) - L sqrt(p_l)',
      'V_lp = xp + y',
      'V(p) piecewise: p | (2√(pKr)-p-K)/(r-1) | K',
      'v(x)=E(V(x)-V(S₀))-H(x-S₀)+F·S₀',
      'IL=(V_lp-V_hold)/V_hold',
      'V_blp=-2L√x',
    ],
    sources: ['936edf03fb', '3f634650d0', '0159507098', '825122fb8a'],
    status: 'research-only',
    feeds: ['liquidity-fingerprint', 'portfolio', 'capital-efficiency'],
  },
  {
    id: 'lp-research-range',
    layer: 'LP',
    label: 'LP 研究区间',
    role: '复用 GetDelta 的动态周期与波动项，在 sqrt-price 空间生成展示区间；仅为研究情景代理，不代表真实 LP 仓位或估值',
    inputs: ['自适应成本锚', 'GetDelta r(T)', '公式周期 formulaHorizonSessions', '历史实现波动率'],
    outputs: ['LP 研究下沿', 'LP 研究上沿', '情景来源与缺失输入'],
    formulas: [
      'rangeFactor = sqrt(r(T))',
      'lpResearchLowerPrice = adaptiveCostAnchor / rangeFactor',
      'lpResearchUpperPrice = adaptiveCostAnchor * rangeFactor',
      'scenario-proxy only; executionAuthority=none; valuationAuthority=none',
    ],
    sources: ['943334771f', 'uniswap-v3-whitepaper'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'liquidity-fingerprint',
    layer: 'LP',
    label: '流动性指纹',
    role: '模型目标仓：展示目标 LP 分配权重和本策略挂单刻度；不是价格概率、市场盘口或链上真实 LP 构成',
    inputs: ['OHLCV 成本锚', '目标分布', '现价', '成本锚', 'Delta/LP 区间', '模拟挂单'],
    outputs: ['混合成分核', '价格层级', '目标分配权重', '指纹统计', '缺失数据提示'],
    formulas: [
      'f(p)=Σ w_c f_c(p)/∫f_c',
      'L_i = ∫_{range_i} f(p) dp / ∫_{lower}^{upper} f(p) dp',
      'f_logLaplace(p)=Laplace(log(p); mu, lambda, kappa)',
      'f_anchor(p)=Normal(log(p); log(anchor), sigma)',
      '待补: 真实 tick 边界、手续费层级、链上 LP 权重',
    ],
    sources: ['0a40cbb0ee', '06b68e5e0e', 'hgjrvacjbe', 'bb63abc148'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'lp-pool-coverage',
    layer: 'LP',
    label: 'LP 池覆盖',
    role: '聚合池快照：用真实池 reserve / volume / 主池占比标注链上覆盖状态',
    inputs: ['poolCoverage.reserveUsd', 'poolCoverage.volumeUsd24h', 'poolCoverage.topPoolReserveShare'],
    outputs: ['turnover24h', 'topReserveShare'],
    formulas: ['turnover24h = volumeUsd24h / reserveUsd', 'topReserveShare = topPoolReserveUsd / reserveUsd'],
    sources: ['geckoterminal-pool-aggregate'],
    status: 'research-only',
    feeds: ['liquidity-fingerprint'],
  },
  {
    id: 'amm-geometry',
    layer: 'AMM',
    label: 'AMM 几何',
    role: '研究不变量、储备曲线、Lambert W 与 Numoen AMM 几何；Numoen 协议机制未验证',
    inputs: ['储备', '不变量', '边界条件'],
    outputs: ['xy=k', 'Lambert W 分支', 'Numoen quoter', 'slippage snapshot'],
    formulas: [
      'x y = k',
      'W(z) e^{W(z)} = z',
      'Lambert curve: y = W(c e^{c(2-x)} / x) / c',
      'Numoen: x/(s·10^3) - (y/s)^2/4 + u·y/s = L',
    ],
    sources: ['50693ae997', '8a2d4257ef', 'c1a8cc5a49', 'cb14bde283'],
    status: 'protocol-unverified',
    feeds: [],
  },
  {
    id: 'capital-efficiency',
    layer: 'LP',
    label: '资本效率',
    role: '比较区间收窄的几何资本效率；恢复 CK 端点比曲线的精确边际拐点，并区分真实当前价口径',
    inputs: ['区间宽度', '偏斜', '估值价格口径'],
    outputs: ['几何中点 CE', '算术中心当前价 CE', '上下界', '边际效率斜率', 'CK 对称拐点'],
    formulas: [
      'CE_geo(x, alpha) = 1 / (1 - ((1-x)/(1+alpha x))^(1/4)); 估值价为 sqrt(PaPb)',
      'CE(P)=2/(2-sqrt(P/Pb)-sqrt(Pa/P)); 用于真实当前价 P',
      'skew=1: x* = sqrt(5+2sqrt(10))/4 = 0.8412994161',
      "CE''(x*)=0; max dx/(-dCE)=1/(-CE'(x*))",
      '精确几何定理；不推出概率覆盖、手续费最优或 PnL 最优',
    ],
    sources: ['ysv2j74j6k', '5ab9c1e3a1'],
    status: 'research-only',
    feeds: ['portfolio'],
  },
  {
    id: 'funding',
    layer: '组合',
    label: '资金费率',
    role: '仅展示 TWAP 估计；未接真实永续资金费率、结算周期和交易所制度',
    inputs: ['perp TWAP', 'spot TWAP', '估计小时'],
    outputs: ['basisFraction', 'cumulativeFundingProxy'],
    formulas: ['basisFraction = perp_twap / spot_twap - 1', 'cumulativeFundingProxy = basisFraction × h / 24'],
    sources: ['fundamentals-perpetual-futures'],
    status: 'proxy-only',
    feeds: [],
  },
  {
    id: 'portfolio',
    layer: '组合',
    label: '组合研究',
    role: '组合研究视图；不作为模拟挂单的输入',
    inputs: ['LP 价值', '期权价值', '对冲规模', '手续费', '资金费率'],
    outputs: ['mark 账本', '入场现金流账本', 'PnL 账本', '局部 Delta', '情景盈亏路径'],
    formulas: [
      'PnL(p,path)=LP_PnL(p)+Option_PnL(p)+Hedge_PnL(p)+RealizedFees(path)-FundingSettlement(path)-Costs(path)',
      'formal total 保持 null，直到 leg premium、币种、名义本金、期限和路径现金流对齐',
    ],
    sources: ['99af67bf76', '0e2beceb89', '722e20ccc4', '825122fb8a', '0159507098', '3f634650d0'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'order-plan',
    layer: '执行',
    label: '模拟挂单',
    role: '只在成本带、GetDelta 带和账户输入同时满足时生成模拟挂单',
    inputs: ['成本带', 'GetDelta 带', '本金', '失效条件'],
    outputs: ['挂买', '挂卖', '观察窗口', '失效线'],
    formulas: ['orders = f(cost_path, delta_band, capital, risk_state)'],
    sources: [],
    status: 'implemented',
    feeds: [],
  },
  {
    id: 'deviation-score',
    layer: '融合',
    label: '偏离强度',
    role: 'Cost × Volatility：价格偏离成本锚的标准差倍数与正态参考极端度；不估计未来回归概率',
    inputs: ['成本偏离', '年化波动', '方向/目标绑定公式周期', '市场年交易会话数'],
    outputs: ['z-score', '偏离百分位', '双尾概率质量', '偏离强度等级'],
    formulas: [
      'z = costDistance / (σ·√(T/TDPY))',
      'percentile = 2Φ(|z|)-1',
      'two-sided tail = 2(1-Φ(|z|))',
      '以上均非条件回归概率',
    ],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'risk-surface',
    layer: '融合',
    label: '风险曲面',
    role: 'Delta Band × Option Greeks：在价格带上展开 Greeks 曲线',
    inputs: [
      '入场价',
      '行权价',
      '独立期权距到期会话 timeToExpirySessions',
      'tradingDaysPerYear',
      'IV',
      '价格带下沿',
      '价格带上沿',
    ],
    outputs: [
      'optionDelta 曲线（标的单位/期权单位）',
      'optionGamma 曲线（delta/标的价格单位）',
      'optionThetaPerSession 曲线（报价币/交易会话/期权单位）',
    ],
    formulas: ['Greeks(price) for price ∈ [bandLow, bandHigh]'],
    sources: ['943334771f', '97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'net-lp-efficiency',
    layer: '融合',
    label: 'LP 研究拆解',
    role: '将 CE 几何与同期限收益归因分列；路径手续费未校准时不输出净收益结论',
    inputs: ['资本效率', '同期限无常损失', '路径手续费收益', '期限/本金口径'],
    outputs: ['CE 几何', 'IL', '手续费归因', '校准缺口'],
    formulas: [
      'geometry: CE (multiple), 不与 return 相加',
      'same-horizon return = IL + realized path fee return',
      'fee≈theta 仅为同币种/期限/名义本金归一后的经济类比，不是恒等式',
      '待补: feeGrowth / 成交路径 / LP share / gas / 再平衡规则',
    ],
    sources: ['ysv2j74j6k', '825122fb8a', 'uniswap-v3-whitepaper'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'net-carry',
    layer: '融合',
    label: '持仓归因情景',
    role: 'Funding × Cost 的研究视图；资金费率未接真实结算制度，不输出真实净收益',
    inputs: ['周期起点/目标/方向', '同周期累计资金代理', 'funding 持仓方向', '共同名义本金与时间基'],
    outputs: ['目标毛收益', '带符号 funding 现金流', '净 carry 情景', '同名义盈亏平衡成本'],
    formulas: [
      'long gross = targetPrice/cycleStartPrice - 1',
      'short gross = (cycleStartPrice-targetPrice)/cycleStartPrice',
      'net = grossRecoveryReturn + signed fundingCashflowReturn',
      'breakEvenFundingNetCostReturn = grossRecoveryReturn',
      '待补: 真实资金费率、对冲腿名义、结算时间、交易所制度',
    ],
    sources: [],
    status: 'proxy-only',
    feeds: [],
  },
  {
    id: 'mean-reversion',
    layer: '二阶',
    label: '均值回归半衰期',
    role: 'AR(1) 样本诊断：满足平稳衰减边界时给出节奏坐标，不预测未来回归时点',
    inputs: ['截至当前会话的成本偏离序列', '相邻交易会话采样步长'],
    outputs: [
      'arCoefficient（无量纲）',
      'arDecayRatePerStep（每交易会话）',
      'halfLifeSessions（交易会话）',
      'decayMode / isMeanReverting 样本门禁',
      'formulaHorizonSessions（交易会话）',
    ],
    formulas: [
      'arCoefficient = Σ(x_{t-1}·x_t) / Σ(x_{t-1}²)',
      'x_t = arCoefficient·x_{t-1} + ε_t',
      'arDecayRatePerStep = -ln(|arCoefficient|)',
      'halfLifeSessions = ln(2) / arDecayRatePerStep',
      '单调衰减门禁: 0 < arCoefficient < 1 且 decayMode = monotonic-decay',
      'q = (targetPrice-entryPrice)/(anchorPrice-entryPrice)',
      'formulaHorizonSessions(q) = halfLifeSessions·log2(1/(1-q))',
    ],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'dynamic-holding-state',
    layer: '二阶',
    label: '动态持仓状态',
    role: '用回撤表征、z、HL 和成本带推导观察/等待/剔除及短线/基金周期；研究 LP/CK 边界不参与目标价',
    inputs: [
      '截至当前会话的 OHLCV 前缀',
      '可选显式情景窗口 lookbackSessions',
      'z-score',
      'halfLifeSessions',
      '成本下沿/成本锚',
    ],
    outputs: ['windowSpec', 'drawdownDepth/speed/repair/age', 'phase', 'milestones', 'holdingPlan', 'blockedReasons'],
    formulas: [
      'window_t = OHLCV_{0:t}（无 lookback 时 expanding-prefix）',
      'window_t = trailing(OHLCV_{0:t}, lookbackSessions)（仅显式情景）',
      'drawdownDepth_t = close_t / max(close in window_t) - 1',
      'fastLagSessions=max(1,⌊∛n⌋); slowLagSessions=min(n-1,max(fast+1,⌊√n⌋))',
      'q(T)=1-2^(-T/halfLifeSessions)',
      'q = (targetPrice-entryPrice)/(anchorPrice-entryPrice)',
      'formulaHorizonSessions(q) = halfLifeSessions·log2(1/(1-q))',
    ],
    sources: [],
    status: 'implemented',
    feeds: ['order-plan'],
  },
  {
    id: 'gamma-pnl',
    layer: '二阶',
    label: 'Gamma PnL / 凸性情景',
    role: '½·Γ·(ΔP)²：按给定单位与名义本金估算凸性情景值，不代表已实现人民币收益',
    inputs: ['Gamma', '标的价格', '价格变动', '仓位规模'],
    outputs: ['Position Gamma', 'Dollar Gamma', 'Gamma PnL', '凸性方向'],
    formulas: [
      'PositionGamma = Γ · positionSize',
      'DollarGamma = PositionGamma · P²',
      'GammaPnL = ½ · PositionGamma · (ΔP)² = ½ · DollarGamma · (ΔP/P)²',
    ],
    sources: ['97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'vol-confidence',
    layer: '二阶',
    label: '历史波动样本区间',
    role: 'σ 的估计误差 ≈ σ/√(2n)：展示历史已实现波动的样本区间，不是市场 IV 区间',
    inputs: ['年化波动', '样本量', '区间水平'],
    outputs: ['标准误', '估计区间', '精度评级'],
    formulas: ['SE(σ) = σ / √(2n)', 'CI = σ ± z·SE'],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['volatility'],
  },
]

export const formulaEdges = formulaStages.flatMap((stage) =>
  stage.feeds.map((target) => ({ source: stage.id, target })),
)

export const formulaCapabilities = [
  {
    id: 'market-path',
    label: '市场路径引擎',
    role: '把 K 线统一成成本、波动和公式路径',
    stages: ['path', 'cost', 'volatility'],
    action: '回答现在离市场成本有多远，波动是否允许挂单。',
  },
  {
    id: 'move-derivative',
    label: '波动定价引擎',
    role: '把任意入场价和方向/结构目标绑定的公式周期翻成价格带；期权敏感度另用独立到期期限',
    stages: ['delta-band', 'option-greeks', 'asian-option'],
    action: '回答应该给价格留多宽、风险曲率来自哪里。',
  },
  {
    id: 'liquidity-amm',
    label: '流动性库存引擎',
    role: '把 LP、AMM 不变量和流动性分布放到同一套库存语言里',
    stages: [
      'lp-inventory',
      'lp-research-range',
      'liquidity-fingerprint',
      'lp-pool-coverage',
      'amm-geometry',
      'capital-efficiency',
    ],
    action: '回答已声明 LP 情景或完整真实仓位的库存、区间效率和再平衡压力。',
  },
  {
    id: 'portfolio-execution',
    label: '组合执行引擎',
    role: '模拟挂单只接成本带、GetDelta 和账户输入；LP/期权/永续仍是研究视图',
    stages: ['funding', 'portfolio', 'order-plan'],
    action: '回答模拟挂单刻度、持仓窗口和失效线；组合研究不参与模拟挂单。',
  },
  {
    id: 'formula-fusion',
    label: '公式融合',
    role: '将两个以上基础公式融合成研究视图，未进入模拟挂单',
    stages: ['deviation-score', 'risk-surface', 'net-lp-efficiency', 'net-carry'],
    action: '回答偏离和风险曲面的观察，不输出默认策略结论。',
  },
  {
    id: 'second-order',
    label: '二阶分析',
    role: '速度 · 凸性 · 不确定性：均值回归、凸性项和波动率区间',
    stages: ['mean-reversion', 'dynamic-holding-state', 'gamma-pnl', 'vol-confidence'],
    action: '展示 AR 样本速度、动态持仓状态、Gamma 情景值和历史波动样本区间。',
  },
]

export function getFormulaCapability(id) {
  return formulaCapabilities.find((item) => item.id === id) ?? formulaCapabilities[0]
}

export function getCapabilityStages(capabilityId) {
  const capability = getFormulaCapability(capabilityId)
  return capability.stages.map(getFormulaStage)
}

export function getFormulaStage(id) {
  return formulaStages.find((stage) => stage.id === id) ?? formulaStages[0]
}
