export const formulaStages = [
  {
    id: 'path',
    layer: '数据',
    label: '价格路径',
    role: '所有公式的共同输入口径',
    inputs: ['OHLCV', '成交量', '时间粒度'],
    outputs: ['对数收益', 'VWAP', '路径窗口'],
    formulas: ['r_t = ln(P_t / P_{t-1})', 'VWAP = sum(PV) / sum(V)', '时间基: 质数 179 / e / π 分解周期'],
    sources: [],
    status: 'implemented',
    feeds: ['cost', 'volatility'],
  },
  {
    id: 'cost',
    layer: '数据',
    label: '市场成本',
    role: '把路径翻译成可交易的成本锚和动态成本带',
    inputs: ['OHLCV', '窗口长度'],
    outputs: ['成本锚', '近端成本', '成本上沿', '成本下沿'],
    formulas: ['Cost_vwap = sum(close * volume) / sum(volume)', 'd_cost = close / Cost_vwap - 1'],
    sources: [],
    status: 'implemented',
    feeds: ['delta-band', 'order-plan', 'portfolio'],
  },
  {
    id: 'volatility',
    layer: '波动',
    label: '波动口径',
    role: '决定挂单间距、期权口径和失效阈值',
    inputs: ['对数收益', 'high/low/close'],
    outputs: ['年化波动', 'ATR', 'VixFix'],
    formulas: ['sigma_ann = std(r_t) * sqrt(365)', 'ATR% = avg(TR / close)', 'VixFix = (highest(close,N)-low)/highest(close,N)'],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['delta-band', 'option-greeks', 'order-plan'],
  },
  {
    id: 'delta-band',
    layer: '波动',
    label: 'GetDelta 成本带',
    role: '用任意入场价、持仓时间、IV 和目标收益生成多空价格带',
    inputs: ['入场价', '持仓 T', 'IV', '目标收益'],
    outputs: ['多头高/成本/低', '空头高/成本/低'],
    formulas: ['e_T = sqrt(T / (365 * 2pi))', 'r_T = ((1 + sigma e_T) / (1 - sigma e_T))^2 * z', 'K = P(d r_T - d + 1)^2 / r_T'],
    sources: ['943334771f', '5baa5607d0', '83418c6ca1'],
    status: 'implemented',
    feeds: ['order-plan', 'portfolio'],
  },
  {
    id: 'option-greeks',
    layer: '期权',
    label: '期权 Greeks',
    role: '把非线性风险拆成可检查的局部敏感度',
    inputs: ['标的价', '行权价', '持仓 T', 'IV', '利率', '分红/资金口径 q'],
    outputs: ['价格', 'Delta', 'Gamma', 'Theta/日', 'Theta/年', 'Vega', 'Rho'],
    formulas: ['d1 = (ln(S/K)+(r-q+sigma^2/2)T)/(sigma sqrt(T))', 'd2 = d1 - sigma sqrt(T)', 'rho_call = K T e^{-rT} N(d2) / 100'],
    sources: ['97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'asian-option',
    layer: '期权',
    label: '亚式近似',
    role: '处理均价结算、Bachelier normal-vol 和 LP payoff 的平滑比较',
    inputs: ['价格路径', '均价窗口', 'IV', 'normal vol', '行权价'],
    outputs: ['Asian price/Delta/Gamma', 'Bachelier price/Delta/Gamma', 'payoff fit 边界'],
    formulas: ['sigma_geo ≈ sigma / sqrt(3)', 'Bachelier: C=e^{-rT}((S-K)N(d)+sigma_N sqrt(T)n(d))', 'd=(S-K)/(sigma_N sqrt(T))'],
    sources: ['97fa8c814b', '99af67bf76', '722e20ccc4', '0e2beceb89'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'lp-inventory',
    layer: 'LP',
    label: 'LP 库存曲线',
    role: '直接计算 LP 持有什么库存，而不是只看无常损失标签',
    inputs: ['价格', '区间下沿', '区间上沿', '流动性 L'],
    outputs: ['x_real', 'y_real', 'LP 价值', '库存 Delta'],
    formulas: ['x = L/sqrt(p) - L/sqrt(p_u)', 'y = L sqrt(p) - L sqrt(p_l)', 'V_lp = xp + y', 'V(p) piecewise: p | (2√(pKr)-p-K)/(r-1) | K', 'v(x)=E(V(x)-V(S₀))-H(x-S₀)+F·S₀', 'IL=(V_lp-V_hold)/V_hold', 'V_blp=-2L√x'],
    sources: ['936edf03fb', '3f634650d0', '0159507098', '825122fb8a'],
    status: 'implemented',
    feeds: ['liquidity-fingerprint', 'portfolio', 'capital-efficiency'],
  },
  {
    id: 'liquidity-fingerprint',
    layer: 'LP',
    label: '流动性指纹',
    role: '模型目标仓：展示目标 LP 密度和本策略挂单刻度；不是市场盘口或链上真实 LP 构成',
    inputs: ['OHLCV 成本锚', '目标分布', '价格网格', 'OrderPlan 挂单'],
    outputs: ['log-Laplace 目标密度', '价格层级', '计划挂单刻度', '缺失数据提示'],
    formulas: ['L_i = ∫_{range_i} f(p) dp / ∫_{lower}^{upper} f(p) dp', 'f_logLaplace(p)=Laplace(log(p); mu, lambda, kappa)', '待补: 真实 tick 边界、手续费层级、链上 LP 权重'],
    sources: ['0a40cbb0ee', '06b68e5e0e', 'hgjrvacjbe', 'bb63abc148'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'amm-geometry',
    layer: 'AMM',
    label: 'AMM 几何',
    role: '研究不变量、储备曲线、Lambert W 与 Numoen AMM 几何；Numoen 协议机制未验证',
    inputs: ['储备', '不变量', '边界条件'],
    outputs: ['xy=k', 'Lambert W 分支', 'Numoen quoter', 'slippage snapshot'],
    formulas: ['x y = k', 'W(z) e^{W(z)} = z', 'Lambert curve: y = W(c e^{c(2-x)} / x) / c', 'Numoen: x/(s·10^3) - (y/s)^2/4 + u·y/s = L'],
    sources: ['50693ae997', '8a2d4257ef', 'c1a8cc5a49', 'cb14bde283'],
    status: 'protocol-unverified',
    feeds: [],
  },
  {
    id: 'capital-efficiency',
    layer: 'LP',
    label: '资本效率',
    role: '比较区间收窄带来的资金效率和维护压力',
    inputs: ['区间宽度', '偏斜'],
    outputs: ['效率倍数', '上下界'],
    formulas: ['CE(x, alpha) = 1 / (1 - ((1-x)/(1+alpha x))^(1/4))'],
    sources: ['696b78e1fd', '5ab9c1e3a1'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'funding',
    layer: '组合',
    label: '资金费率',
    role: '仅展示 TWAP 估计；未接真实永续资金费率、结算周期和交易所制度',
    inputs: ['perp TWAP', 'spot TWAP', '估计小时'],
    outputs: ['TWAP 偏离估计', '粗略资金成本'],
    formulas: ['research ratio = perp_twap / spot_twap - 1', 'estimated_cost = ratio * h / 24'],
    sources: [],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'portfolio',
    layer: '组合',
    label: '组合价值',
    role: '组合研究视图；不作为默认挂单计划的输入',
    inputs: ['LP 价值', '期权价值', '对冲规模', '手续费', '资金费率'],
    outputs: ['组合曲线', '局部 Delta', '盈亏路径'],
    formulas: ['Portfolio(p)=LP(p)+Option(p)-H(p-p0)+Fees-Funding', 'curve(p)=lpPnl(p)+optionLeg(p)+hedgePnl(p)+fees-funding'],
    sources: ['99af67bf76', '0e2beceb89', '722e20ccc4', '825122fb8a', '0159507098', '3f634650d0'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'order-plan',
    layer: '执行',
    label: '挂单计划',
    role: '只在公式图通过后生成挂买、挂卖、拿多久和失效线',
    inputs: ['成本带', 'GetDelta 带', '本金', '失效条件'],
    outputs: ['挂买', '挂卖', '观察窗口', '失效线'],
    formulas: ['orders = f(cost_path, delta_band, capital, risk_state)'],
    sources: [],
    status: 'implemented',
    feeds: [],
  },
  {
    id: 'deviation-score',
    layer: '融合',
    label: '偏离强度',
    role: 'Cost × Volatility：价格偏离成本锚的标准差倍数，回归概率估计',
    inputs: ['成本偏离', '年化波动', '持仓天数'],
    outputs: ['z-score', '回归概率', '偏离强度等级'],
    formulas: ['z = costDistance / (σ·√(T/365))', 'P(回归) = Φ(|z|)'],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'risk-surface',
    layer: '融合',
    label: '风险曲面',
    role: 'Delta Band × Option Greeks：在价格带上展开 Greeks 曲线',
    inputs: ['入场价', '行权价', 'IV', '价格带下沿', '价格带上沿'],
    outputs: ['Delta 曲线', 'Gamma 曲线', 'Theta 曲线'],
    formulas: ['Greeks(price) for price ∈ [bandLow, bandHigh]'],
    sources: ['943334771f', '97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'net-lp-efficiency',
    layer: '融合',
    label: 'LP 净效率',
    role: 'IL × CE 的研究视图；未完成真实 LP 区间权重、手续费和再平衡规则',
    inputs: ['资本效率', '无常损失', '预期手续费'],
    outputs: ['毛效率估计', '净效率估计', '研究提示'],
    formulas: ['research net = (CE-1) + IL + CE·fee', '待补: 区间权重、手续费制度、离散 LP 规则'],
    sources: ['696b78e1fd', '825122fb8a'],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'net-carry',
    layer: '融合',
    label: '持仓净收益',
    role: 'Funding × Cost 的研究视图；资金费率未接真实结算制度',
    inputs: ['成本偏离', '资金费率', '持仓天数'],
    outputs: ['净收益估计', '资金成本估计', '研究提示'],
    formulas: ['research net = |costDistance| - |funding|×T/365', '待补: 真实资金费率、结算时间、交易所制度'],
    sources: [],
    status: 'research-only',
    feeds: [],
  },
  {
    id: 'mean-reversion',
    layer: '二阶',
    label: '均值回归半衰期',
    role: 'e/π/质数结构：AR(1) 估计回归速度，半衰期 = ln(2)/θ，以质数天衡量',
    inputs: ['成本偏离序列', '年时间基'],
    outputs: ['ρ 自回归系数', 'θ 回归速度', '半衰期天数', '速度评级'],
    formulas: ['x_t = ρ·x_{t-1} + ε', 'θ = -ln(|ρ|)', 't½ = ln(2)/θ'],
    sources: [],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'gamma-pnl',
    layer: '二阶',
    label: 'Gamma PnL / 凸性收益',
    role: '½·Γ·(ΔP)² ：凸性头寸的实际波动收益，连接方差结构与 π',
    inputs: ['Gamma', '价格变动', '仓位规模'],
    outputs: ['Dollar Gamma', 'Gamma PnL', '凸性方向'],
    formulas: ['GammaPnL = ½ · Γ · (ΔP)² · positionSize'],
    sources: ['97fa8c814b'],
    status: 'implemented',
    feeds: ['portfolio'],
  },
  {
    id: 'vol-confidence',
    layer: '二阶',
    label: '波动率置信',
    role: 'σ 的估计误差 ≈ σ/√(2n)：我们看到的 41% 波动率到底有多准？',
    inputs: ['年化波动', '样本量', '置信水平'],
    outputs: ['标准误', '置信区间', '精度评级'],
    formulas: ['SE(σ) = σ / √(2n)', 'CI = σ ± z·SE'],
    sources: ['hgjrvacjbe'],
    status: 'implemented',
    feeds: ['volatility'],
  },
]

export const formulaEdges = formulaStages.flatMap((stage) =>
  stage.feeds.map((target) => ({ source: stage.id, target })),
)

export const formulaCapabilities = [
  {
    id: 'market-path',
    label: '市场路径引擎',
    role: '把 K 线统一成成本、波动和公式路径',
    stages: ['path', 'cost', 'volatility'],
    action: '回答现在离市场成本有多远，波动是否允许挂单。',
  },
  {
    id: 'move-derivative',
    label: '波动定价引擎',
    role: '把任意入场价和持仓时间翻成价格带、期权敏感度和均价结构',
    stages: ['delta-band', 'option-greeks', 'asian-option'],
    action: '回答应该给价格留多宽、风险曲率来自哪里。',
  },
  {
    id: 'liquidity-amm',
    label: '流动性库存引擎',
    role: '把 LP、AMM 不变量和流动性分布放到同一套库存语言里',
    stages: ['lp-inventory', 'liquidity-fingerprint', 'amm-geometry', 'capital-efficiency'],
    action: '回答 LP 实际持仓、区间效率和再平衡压力。',
  },
  {
    id: 'portfolio-execution',
    label: '组合执行引擎',
    role: '挂单计划只接成本带和 GetDelta；LP/期权/永续仍是研究视图',
    stages: ['funding', 'portfolio', 'order-plan'],
    action: '回答默认挂单的数量、持仓窗口和失效线；组合研究不参与默认挂单。',
  },
  {
    id: 'formula-fusion',
    label: '公式融合',
    role: '将两个以上基础公式融合成研究视图，未进入默认挂单',
    stages: ['deviation-score', 'risk-surface', 'net-lp-efficiency', 'net-carry'],
    action: '回答偏离和风险曲面的观察，不输出默认策略结论。',
  },
  {
    id: 'second-order',
    label: '二阶分析',
    role: '速度 · 凸性 · 不确定性：均值回归多快？凸性赚多少？波动率估计多准？',
    stages: ['mean-reversion', 'gamma-pnl', 'vol-confidence'],
    action: '回答回归速度、Gamma 收益和波动率置信度——e/π/质数结构在此体现。',
  },
]

export function getFormulaCapability(id) {
  return formulaCapabilities.find((item) => item.id === id) ?? formulaCapabilities[0]
}

export function getCapabilityStages(capabilityId) {
  const capability = getFormulaCapability(capabilityId)
  return capability.stages.map(getFormulaStage)
}

export function getFormulaStage(id) {
  return formulaStages.find((stage) => stage.id === id) ?? formulaStages[0]
}
