export const CHART_OVERLAY_TOGGLES = [
  { key: 'priceBands', label: '价格带组' },
  { key: 'greeksPane', label: '期权希腊值子图' },
  { key: 'lpPane', label: 'LP情景库存子图' },
  { key: 'carryPane', label: '资金费率子图' },
  { key: 'executionMarkers', label: '执行标记' },
  { key: 'researchMarkers', label: '研究标记' },
  { key: 'costBand', label: '成本锚带' },
  { key: 'causalEquilibrium', label: '价格滤波参考' },
  { key: 'statisticalCenter', label: '统计回归中心' },
  { key: 'vwapCost', label: '成交量加权重心' },
  { key: 'cohortCost', label: '随机换手存续成本代理' },
  { key: 'supplyDemand', label: '供需均衡参数场景' },
  { key: 'fundamental', label: '基本面估值参数场景' },
  { key: 'entryLine', label: '入场价线' },
  { key: 'volBand', label: '动态周期 GetDelta 带' },
  { key: 'lpBand', label: 'LP 动态公式研究区间' },
  { key: 'volume', label: '成交量' },
  { key: 'stockChipProfile', label: '个股筹码图' },
  { key: 'replayMarkers', label: '回放标记' },
  { key: 'replayMarkerLabels', label: '回放文字' },
  { key: 'currentDecision', label: '当前状态点' },
  { key: 'equityPane', label: '权益子图' },
  { key: 'kdjPane', label: 'KDJ随机指标子图' },
  { key: 'rsiPane', label: 'RSI相对强弱子图' },
]

export const CHART_OVERLAY_KEYS = CHART_OVERLAY_TOGGLES.map((toggle) => toggle.key)
