#!/usr/bin/env node
// Convert public CSV datasets into JS modules so Vite owns data delivery.
// This avoids static hosting rewrite rules treating CSV files as SPA routes.

import { rm, mkdir, readdir, readFile, rename, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SOURCE_DIR = join(ROOT, 'public', 'data')
const TARGET_DIR = join(ROOT, 'src', 'data', 'generated')
const TEMP_DIR = join(ROOT, 'src', 'data', `.generated-${process.pid}-${Date.now()}`)
const CSV_MODULE_DIR = join(TEMP_DIR, 'csv')
const INDEX_PATH = join(TEMP_DIR, 'market-csv-index.js')
const REQUIRED_SAMPLE = 'btcusdt-1d-2017-2025.csv'

await mkdir(CSV_MODULE_DIR, { recursive: true })

const files = (await readdir(SOURCE_DIR)).filter((file) => file.endsWith('.csv')).sort()
const entries = []

for (const file of files) {
  const text = await readFile(join(SOURCE_DIR, file), 'utf8')
  const moduleName = `${safeModuleName(file)}.js`
  await writeFile(join(CSV_MODULE_DIR, moduleName), `export default ${JSON.stringify(text)}\n`)
  entries.push([file, moduleName])
}

const required = entries.find(([file]) => file === REQUIRED_SAMPLE)
if (!required) {
  console.error(`missing required CSV sample: ${REQUIRED_SAMPLE}`)
  process.exit(1)
}

const loaderEntries = entries
  .flatMap(([file, moduleName]) => [
    [file, moduleName],
    [`/data/${file}`, moduleName],
    [`/datasets/${file}`, moduleName],
    [`/datasets/${file}.txt`, moduleName],
  ])
  .map(([key, moduleName]) => `${JSON.stringify(key)}:()=>import(${JSON.stringify(`./csv/${moduleName}`)})`)
  .join(',')

const fileList = JSON.stringify(entries.map(([file]) => file))

await writeFile(INDEX_PATH, [
  '// Generated by scripts/csv2js.mjs. Do not edit by hand.',
  `const loaders={${loaderEntries}}`,
  `export const marketCsvFiles=${fileList}`,
  'export async function loadMarketCsv(url){const key=normalizeDataUrl(url);const loader=loaders[key]||loaders[fileNameOf(key)];if(!loader)return null;const mod=await loader();return mod.default}',
  'function normalizeDataUrl(url){return String(url??"").split("#",1)[0].split("?",1)[0]}',
  'function fileNameOf(url){return normalizeDataUrl(url).split("/").at(-1)?.replace(/\\.txt$/i,"")??""}',
  '',
].join('\n'))

await rm(TARGET_DIR, { recursive: true, force: true })
await rename(TEMP_DIR, TARGET_DIR)

const requiredText = await readFile(join(SOURCE_DIR, REQUIRED_SAMPLE), 'utf8')
const firstLine = requiredText.split(/\r?\n/, 1)[0] ?? ''
if (!/^\d{10,13},/.test(firstLine)) {
  console.error(`${REQUIRED_SAMPLE} does not look like Binance kline CSV`)
  process.exit(1)
}

console.log(`generated ${entries.length} CSV JS modules`)

function safeModuleName(file) {
  return file.replace(/[^A-Za-z0-9_$]/g, '_')
}
